export const ChallengeStatus = { OPEN: "OPEN", ACCEPTED: "ACCEPTED", CANCELLED: "CANCELLED", EXPIRED: "EXPIRED" } as const;
export const MatchStatus = { OPEN: "OPEN", ACCEPTED: "ACCEPTED", READY: "READY", IN_PROGRESS: "IN_PROGRESS", COMPLETED: "COMPLETED", CANCELLED: "CANCELLED", EXPIRED: "EXPIRED", DISPUTED: "DISPUTED" } as const;
export const DisputeStatus = { OPEN: "OPEN", UNDER_REVIEW: "UNDER_REVIEW", RESOLVED: "RESOLVED" } as const;
export const LedgerDirection = { CREDIT: "CREDIT", DEBIT: "DEBIT" } as const;
export const LedgerTransactionType = { CREDIT_GRANT: "CREDIT_GRANT", MATCH_STAKE_RESERVE: "MATCH_STAKE_RESERVE", MATCH_STAKE_RELEASE: "MATCH_STAKE_RELEASE", MATCH_WIN_SETTLEMENT: "MATCH_WIN_SETTLEMENT", MATCH_DRAW_REFUND: "MATCH_DRAW_REFUND", ADMIN_ADJUSTMENT: "ADMIN_ADJUSTMENT", SEASON_REWARD: "SEASON_REWARD" } as const;
export const MatchOutcome = { WINNER_PLAYER_1: "WINNER_PLAYER_1", WINNER_PLAYER_2: "WINNER_PLAYER_2", DRAW: "DRAW", CANCELLED: "CANCELLED", CHEAT_FLAG: "CHEAT_FLAG", DISCONNECT_FORFEIT_PLAYER_1: "DISCONNECT_FORFEIT_PLAYER_1", DISCONNECT_FORFEIT_PLAYER_2: "DISCONNECT_FORFEIT_PLAYER_2" } as const;
