export enum MatchOutcomeEnum {
  WINNER_PLAYER_1 = "WINNER_PLAYER_1",
  WINNER_PLAYER_2 = "WINNER_PLAYER_2",
  DRAW = "DRAW",
  CANCELLED = "CANCELLED",
  CHEAT_FLAG = "CHEAT_FLAG",
  DISCONNECT_FORFEIT_PLAYER_1 = "DISCONNECT_FORFEIT_PLAYER_1",
  DISCONNECT_FORFEIT_PLAYER_2 = "DISCONNECT_FORFEIT_PLAYER_2"
}
